export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f5f7fb",
    padding: "32px",
  },
  panel: {
    maxWidth: "1000px",
    margin: "0 auto",
    background: "#ffffff",
    border: "1px solid #dfe4ea",
    borderRadius: "8px",
    padding: "32px",
    boxShadow: "0 12px 32px rgba(15, 23, 42, 0.08)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    alignItems: "flex-start",
    marginBottom: "24px",
    flexWrap: "wrap",
  },
  eyebrow: {
    margin: "0 0 8px",
    color: "#2563eb",
    fontWeight: 700,
    textTransform: "uppercase",
    fontSize: "13px",
  },
  title: {
    margin: "0 0 12px",
    color: "#111827",
    fontSize: "30px",
  },
  description: {
    margin: 0,
    color: "#4b5563",
    fontSize: "16px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap: "16px",
    marginBottom: "24px",
  },
  infoBox: {
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "20px",
    background: "#f9fafb",
  },
  sectionTitle: {
    margin: "0 0 16px",
    color: "#111827",
    fontSize: "20px",
  },
  infoList: {
    display: "grid",
    gap: "12px",
  },
  resumeActions: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: "18px",
  },
  hiddenInput: {
    display: "none",
  },
  profileItem: {
    display: "grid",
    gap: "4px",
  },
  profileLabel: {
    color: "#6b7280",
    fontSize: "13px",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  profileValue: {
    color: "#111827",
    fontSize: "15px",
    overflowWrap: "anywhere",
  },
  form: {
    display: "grid",
    gap: "16px",
    borderTop: "1px solid #e5e7eb",
    paddingTop: "24px",
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
  },
  label: {
    display: "grid",
    gap: "8px",
    color: "#1f2937",
    fontWeight: 600,
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "12px",
    fontSize: "15px",
  },
  textarea: {
    width: "100%",
    minHeight: "110px",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "12px",
    fontSize: "15px",
    fontFamily: "inherit",
    resize: "vertical",
  },
  button: {
    border: "0",
    borderRadius: "6px",
    padding: "12px 16px",
    background: "#2563eb",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: 700,
    cursor: "pointer",
    justifySelf: "start",
  },
  viewButton: {
    borderRadius: "6px",
    padding: "11px 14px",
    background: "#ecfdf5",
    color: "#047857",
    fontSize: "15px",
    fontWeight: 700,
    textDecoration: "none",
  },
  secondaryButton: {
    borderRadius: "6px",
    padding: "10px 14px",
    background: "#e0ecff",
    color: "#1d4ed8",
    fontSize: "14px",
    fontWeight: 700,
    textDecoration: "none",
  },
  error: {
    marginBottom: "16px",
    borderRadius: "6px",
    padding: "12px",
    background: "#fee2e2",
    color: "#991b1b",
  },
  success: {
    marginBottom: "16px",
    borderRadius: "6px",
    padding: "12px",
    background: "#dcfce7",
    color: "#166534",
  },
  progressWrap: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    marginTop: "16px",
  },
  progressTrack: {
    flex: 1,
    height: "10px",
    overflow: "hidden",
    borderRadius: "999px",
    background: "#e5e7eb",
  },
  progressFill: {
    height: "100%",
    borderRadius: "999px",
    background: "#2563eb",
    transition: "width 0.2s ease",
  },
  progressText: {
    minWidth: "44px",
    color: "#4b5563",
    fontSize: "14px",
    fontWeight: 700,
    textAlign: "right",
  },
};
