export const styles = {
  panel: {
    maxWidth: "1180px",
    margin: "0 auto",
    background: "#ffffff",
    border: "1px solid #dfe4ea",
    borderRadius: "8px",
    padding: "32px",
    boxShadow: "0 12px 32px rgba(15, 23, 42, 0.08)",
  },
  header: {
    marginBottom: "24px",
  },
  eyebrow: {
    margin: "0 0 8px",
    color: "#2563eb",
    fontWeight: 700,
    textTransform: "uppercase",
    fontSize: "13px",
  },
  title: {
    margin: "0 0 12px",
    color: "#111827",
    fontSize: "30px",
  },
  description: {
    margin: 0,
    color: "#4b5563",
    fontSize: "16px",
  },
  selectorSection: {
    maxWidth: "620px",
    marginBottom: "24px",
  },
  label: {
    display: "grid",
    gap: "8px",
    color: "#1f2937",
    fontWeight: 600,
  },
  select: {
    width: "100%",
    minHeight: "46px",
    boxSizing: "border-box",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "10px 12px",
    background: "#ffffff",
    color: "#111827",
    fontSize: "15px",
  },
  criteriaBand: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "16px",
    alignItems: "start",
    marginBottom: "20px",
    borderTop: "1px solid #e5e7eb",
    borderBottom: "1px solid #e5e7eb",
    padding: "18px 0",
  },
  criteriaLabel: {
    display: "block",
    marginBottom: "6px",
    color: "#6b7280",
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  criteriaValue: {
    display: "block",
    color: "#111827",
    fontSize: "15px",
    lineHeight: 1.45,
    overflowWrap: "anywhere",
  },
  countBlock: {
    borderLeft: "3px solid #2563eb",
    paddingLeft: "14px",
  },
  count: {
    display: "block",
    color: "#1d4ed8",
    fontSize: "28px",
    lineHeight: 1,
  },
  tableWrap: {
    overflowX: "auto",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
  },
  table: {
    width: "100%",
    minWidth: "1050px",
    borderCollapse: "collapse",
    background: "#ffffff",
  },
  tableHead: {
    padding: "14px 16px",
    background: "#f8fafc",
    borderBottom: "1px solid #e5e7eb",
    color: "#374151",
    fontSize: "13px",
    textAlign: "left",
    textTransform: "uppercase",
  },
  tableCell: {
    padding: "16px",
    borderBottom: "1px solid #eef2f7",
    color: "#111827",
    fontSize: "15px",
    lineHeight: 1.5,
    verticalAlign: "top",
  },
  mutedText: {
    display: "block",
    marginTop: "5px",
    color: "#6b7280",
    fontSize: "14px",
  },
  warningText: {
    display: "block",
    marginTop: "5px",
    color: "#b45309",
    fontSize: "13px",
    fontWeight: 600,
  },
  link: {
    color: "#1d4ed8",
    fontWeight: 600,
  },
  emptyState: {
    border: "1px dashed #cbd5e1",
    borderRadius: "8px",
    padding: "24px",
    color: "#4b5563",
    background: "#f8fafc",
    textAlign: "center",
  },
  error: {
    marginBottom: "16px",
    borderRadius: "6px",
    padding: "12px",
    background: "#fee2e2",
    color: "#991b1b",
  },
  warning: {
    marginBottom: "16px",
    borderRadius: "6px",
    padding: "12px",
    background: "#fef3c7",
    color: "#92400e",
  },
};
