export const styles = {
  page: {
    minHeight: "100vh",
    background: "#f5f7fb",
    padding: "32px",
  },
  panel: {
    maxWidth: "1040px",
    margin: "0 auto",
    background: "#ffffff",
    border: "1px solid #dfe4ea",
    borderRadius: "8px",
    padding: "32px",
    boxShadow: "0 12px 32px rgba(15, 23, 42, 0.08)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    alignItems: "flex-start",
    flexWrap: "wrap",
    marginBottom: "24px",
  },
  headerActions: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
  },
  eyebrow: {
    margin: "0 0 8px",
    color: "#2563eb",
    fontWeight: 700,
    textTransform: "uppercase",
    fontSize: "13px",
  },
  title: {
    margin: "0 0 12px",
    color: "#111827",
    fontSize: "30px",
  },
  description: {
    margin: 0,
    color: "#4b5563",
    fontSize: "16px",
  },
  driveGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "16px",
  },
  driveCard: {
    display: "grid",
    gap: "18px",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
    padding: "20px",
    background: "#f9fafb",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "flex-start",
  },
  companyName: {
    margin: "0 0 6px",
    color: "#111827",
    fontSize: "20px",
  },
  role: {
    margin: 0,
    color: "#4b5563",
    fontSize: "15px",
  },
  eligibleBadge: {
    borderRadius: "999px",
    padding: "6px 10px",
    background: "#dcfce7",
    color: "#166534",
    fontSize: "13px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  blockedBadge: {
    borderRadius: "999px",
    padding: "6px 10px",
    background: "#fee2e2",
    color: "#991b1b",
    fontSize: "13px",
    fontWeight: 700,
    whiteSpace: "nowrap",
  },
  requirements: {
    display: "grid",
    gap: "10px",
  },
  infoItem: {
    display: "grid",
    gap: "4px",
  },
  infoLabel: {
    color: "#6b7280",
    fontSize: "12px",
    fontWeight: 700,
    textTransform: "uppercase",
  },
  infoValue: {
    color: "#111827",
    fontSize: "15px",
    lineHeight: 1.5,
  },
  footer: {
    minHeight: "42px",
    display: "flex",
    alignItems: "center",
  },
  button: {
    border: "0",
    borderRadius: "6px",
    padding: "11px 16px",
    background: "#2563eb",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
  },
  secondaryButton: {
    borderRadius: "6px",
    padding: "10px 14px",
    background: "#e0ecff",
    color: "#1d4ed8",
    fontSize: "14px",
    fontWeight: 700,
    textDecoration: "none",
  },
  appliedText: {
    borderRadius: "6px",
    padding: "10px 14px",
    background: "#ecfdf5",
    color: "#047857",
    fontSize: "15px",
    fontWeight: 700,
  },
  withdrawnText: {
    borderRadius: "6px",
    padding: "10px 14px",
    background: "#e5e7eb",
    color: "#374151",
    fontSize: "14px",
    fontWeight: 700,
  },
  notEligibleText: {
    color: "#6b7280",
    fontSize: "14px",
    lineHeight: 1.5,
  },
  emptyState: {
    border: "1px dashed #cbd5e1",
    borderRadius: "8px",
    padding: "24px",
    color: "#4b5563",
    background: "#f8fafc",
    textAlign: "center",
  },
  error: {
    marginBottom: "16px",
    borderRadius: "6px",
    padding: "12px",
    background: "#fee2e2",
    color: "#991b1b",
  },
  success: {
    marginBottom: "16px",
    borderRadius: "6px",
    padding: "12px",
    background: "#dcfce7",
    color: "#166534",
  },
};
